# Generated by Django 4.0.4 on 2023-10-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('porcentaje', models.FloatField()),
                ('resultado', models.FloatField(null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deduccion',
                'verbose_name_plural': 'Deducciones',
                'ordering': ['fecha'],
            },
        ),
    ]
