# Generated by Django 4.0.4 on 2023-10-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('porcentaje', models.FloatField()),
                ('resultado', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
