# Generated by Django 4.0.4 on 2023-10-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suma',
            options={'verbose_name': 'comida', 'verbose_name_plural': 'comidas'},
        ),
    ]
