# Generated by Django 4.0.4 on 2023-07-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suma',
            options={'verbose_name': 'Suma', 'verbose_name_plural': 'Sumas'},
        ),
    ]
