# Generated by Django 4.0.4 on 2023-10-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suma', '0002_alter_suma_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suma',
            options={'ordering': ['fecha'], 'verbose_name': 'comida', 'verbose_name_plural': 'comidas'},
        ),
        migrations.AlterField(
            model_name='suma',
            name='resultado',
            field=models.FloatField(null=True),
        ),
    ]
