# Generated by Django 4.0.4 on 2024-04-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suma', '0003_alter_suma_options_alter_suma_resultado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suma',
            options={'ordering': ['fecha'], 'verbose_name': 'suma', 'verbose_name_plural': 'sumas'},
        ),
    ]
